apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1
spec:
  selector:
    matchLabels:
      app: svc1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
        - name: svc1
          image: svc:1.0
          envFrom:
            - configMapRef:
                name: svc1
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: svc1-service
spec:
  type: NodePort
  selector:
    app: svc1
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 30000

      # nodePort value must be within 30000 - 32000
      nodePort: 30000
